#!/usr/bin/env bash
# Package overlay/ into a zip for upload to the Twitch Developer Console
# (Extensions > Asset Hosting / Hosted Test).
#
# Bakes the real HTTPS EBS URL into js/ebs-config.js at package time (Twitch's
# extension CSP forbids inline scripts, so the URL can't be set inline in
# overlay.html). Excludes the *.local-test.* dev harness. Refuses to build a
# zip that still contains the placeholder URL.
#
# Usage:
#   EBS_BASE_URL=https://your-ebs.example.com ./overlay/package.sh
#   ./overlay/package.sh --ebs-url https://your-ebs.example.com [--out path/to.zip]
set -euo pipefail

PLACEHOLDER='https://YOUR-EBS-URL-HERE'
OVERLAY_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

EBS_URL="${EBS_BASE_URL:-}"
OUT="$OVERLAY_DIR/../dist/extension.zip"

while [ $# -gt 0 ]; do
  case "$1" in
    --ebs-url) EBS_URL="$2"; shift 2 ;;
    --out)     OUT="$2";     shift 2 ;;
    -h|--help) grep '^#' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

# --- validate the EBS URL ----------------------------------------------------
if [ -z "$EBS_URL" ]; then
  echo "ERROR: no EBS URL given. Set EBS_BASE_URL or pass --ebs-url <url>." >&2
  echo "       (this is the HTTPS URL where ../ebs is reachable; must also be" >&2
  echo "        on the Twitch console's Allowlist for URL Fetching Domains.)" >&2
  exit 1
fi
case "$EBS_URL" in
  https://*) : ;;
  *) echo "ERROR: EBS URL must be https:// (Twitch blocks mixed content): $EBS_URL" >&2; exit 1 ;;
esac
if [ "$EBS_URL" = "$PLACEHOLDER" ]; then
  echo "ERROR: EBS URL is still the placeholder ($PLACEHOLDER)." >&2
  exit 1
fi

# --- stage a clean copy, inject the URL, zip from the staging dir ------------
STAGE="$(mktemp -d)"
trap 'rm -rf "$STAGE"' EXIT

cp -R "$OVERLAY_DIR/." "$STAGE/"
rm -f "$STAGE"/*.local-test.* "$STAGE"/js/*.local-test.* "$STAGE/package.sh"
find "$STAGE" -name '.DS_Store' -delete

cat > "$STAGE/js/ebs-config.js" <<EOF
/* Generated by overlay/package.sh — do not edit. */
window.EBS_BASE_URL = '$EBS_URL';
EOF

mkdir -p "$(dirname "$OUT")"
OUT="$(cd "$(dirname "$OUT")" && pwd)/$(basename "$OUT")"
rm -f "$OUT"
( cd "$STAGE" && zip -rq "$OUT" . )

# --- verify the built zip is actually shippable ------------------------------
if unzip -p "$OUT" js/ebs-config.js | grep -q "$PLACEHOLDER"; then
  echo "ERROR: built zip still contains the placeholder URL — aborting." >&2
  rm -f "$OUT"; exit 1
fi
if unzip -l "$OUT" | grep -q 'local-test'; then
  echo "ERROR: built zip contains a local-test file — aborting." >&2
  rm -f "$OUT"; exit 1
fi

echo "Wrote $OUT"
echo "EBS_BASE_URL baked in: $EBS_URL"
echo
unzip -l "$OUT"
